- hosts: servere 
  become: true
  roles:
    - name: do374ns.mycoll.websetup
  tasks:
    - ansible.posix.firewalld:
        service: http
        immeditate: true
        permanent: true
        state: enabled
