- hosts: servere 
  become: true
  roles:
    - name: do374ns.mycoll.websetup
      tags:
        - testrole
  tasks:
    - ansible.posix.firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled
